AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The model and prompt evaluation solution
Parameters:
  ProjectName:
    AllowedPattern: '[A-Za-z0-9-]{1,16}'
    ConstraintDescription: >-
      Maximum of 22 alphanumeric characters. Can include hyphens (-), but not
      spaces. Must be unique within your account in an AWS Region.
    Description: Project Name used to identify your resources
    MaxLength: '16'
    MinLength: '1'
    Type: String
    Default: LLM-Eval
  pCodeBucket:
    Type: String
    Description: The bucket for initial code repo.
  pCodeKey:
    Type: String
    Description: The Object key for the code
  VpcCIDR:
    Type: String
    Default: 10.2.0.0/16
  PublicSubnetCIDRA:
    Type: String
    Default: 10.2.0.0/24
  PrivateSubnetCIDRA:
    Type: String
    Default: 10.2.1.0/24
  PublicSubnetCIDRB:
    Type: String
    Default: 10.2.2.0/24
  PrivateSubnetCIDRB:
    Type: String
    Default: 10.2.3.0/24

Resources:
  # VPC relates resources
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-vpc'
  PublicSubnetA:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: !Ref PublicSubnetCIDRA
      VpcId: !Ref VPC
      AvailabilityZone: !Sub '${AWS::Region}a'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-subnet-a'
  PublicSubnetB:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: !Ref PublicSubnetCIDRB
      VpcId: !Ref VPC
      AvailabilityZone: !Sub '${AWS::Region}b'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-subnet-b'
  PrivateSubnetA:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: !Ref PrivateSubnetCIDRA
      VpcId: !Ref VPC
      AvailabilityZone: !Sub '${AWS::Region}a'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-private-subnet-a'
  PrivateSubnetB:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: !Ref PrivateSubnetCIDRB
      VpcId: !Ref VPC
      AvailabilityZone: !Sub '${AWS::Region}b'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-private-subnet-b'
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  ElasticIPAddress:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: VPC
  NatGateway:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: !GetAtt ElasticIPAddress.AllocationId
      SubnetId: !Ref PublicSubnetA
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-NAT'
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Public
  PublicRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PrivateRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Private
  PrivateRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway
  PublicSubnetARouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable
  PrivateSubnetARouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRouteTable
  PublicSubnetBRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRouteTable
  PrivateSubnetBRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PrivateSubnetB
      RouteTableId: !Ref PrivateRouteTable
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: security group for SageMaker Model
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-model-security-group'
  SecurityGroupIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: '-1'
      GroupId: !Ref SecurityGroup
      SourceSecurityGroupId: !Ref SecurityGroup

  EvaluationBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        Fn::Sub: 'llm-evaluation-result-${AWS::AccountId}-${AWS::Region}'
  LLMRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: LLM-Repo
      RepositoryDescription: This is a repository for LLM evaluation.
      Code:
        BranchName: main
        S3:
          Bucket: !Ref pCodeBucket
          Key: !Ref pCodeKey
  LLMInvocationStatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                # TODO: narrow down
                Resource: "*"
        - PolicyName: StatesLogPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DeleteResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                  - logs:CreateLogGroup
                Resource: "*"
        - PolicyName: CodecommitRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codecommit:GetFile
                Resource: !GetAtt LLMRepo.Arn
  InvokeLLMStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: Invoke-LLM
      DefinitionString:
        Fn::Sub:
          - |-
            {
              "Comment": "Invoke LLM",
              "StartAt": "GetPrompts",
              "States": {
                "GetPrompts": {
                  "Type": "Task",
                  "Parameters": {
                    "FilePath": "evaluation_artifacts/evaluation_prompt.csv",
                    "RepositoryName": "LLM-Repo"
                  },
                  "Resource": "arn:aws:states:::aws-sdk:codecommit:getFile",
                  "ResultSelector": {
                    "prompts.$": "$.FileContent"
                  },
                  "ResultPath": "$.prompts",
                  "Next": "convert_to_json"
                },
                "convert_to_json": {
                  "Type": "Task",
                  "Resource": "arn:aws:states:::lambda:invoke",
                  "OutputPath": "$.Payload",
                  "Parameters": {
                    "FunctionName": "${ConvertToJsonLambdaArn}",
                    "Payload": {
                      "executionId.$": "$$.Execution.Id",
                      "input.$": "$"
                    }
                  },
                  "Retry": [
                    {
                      "ErrorEquals": [
                        "Lambda.ServiceException",
                        "Lambda.AWSLambdaException",
                        "Lambda.SdkClientException",
                        "Lambda.TooManyRequestsException"
                      ],
                      "IntervalSeconds": 1,
                      "MaxAttempts": 3,
                      "BackoffRate": 2
                    }
                  ],
                  "Next": "Map"
                },
                "Map": {
                  "Type": "Map",
                  "ItemProcessor": {
                    "ProcessorConfig": {
                      "Mode": "INLINE"
                    },
                    "StartAt": "invoke_llm",
                    "States": {
                      "invoke_llm": {
                        "Type": "Task",
                        "Resource": "arn:aws:states:::lambda:invoke",
                        "OutputPath": "$.Payload",
                        "Parameters": {
                          "Payload.$": "$",
                          "FunctionName": "${InvokeLambdaArn}"
                        },
                        "Retry": [
                          {
                            "ErrorEquals": [
                              "Lambda.ServiceException",
                              "Lambda.AWSLambdaException",
                              "Lambda.SdkClientException",
                              "Lambda.TooManyRequestsException"
                            ],
                            "IntervalSeconds": 1,
                            "MaxAttempts": 3,
                            "BackoffRate": 2
                          }
                        ],
                        "End": true
                      }
                    }
                  },
                  "ItemsPath": "$.result",
                  "End": true
                }
              }
            }
          - {
            InvokeLambdaArn: !GetAtt InvokeLLM.Arn,
            ConvertToJsonLambdaArn: !GetAtt ConvertToJson.Arn
          }
      RoleArn: !GetAtt LLMInvocationStatesExecutionRole.Arn
  LLMIEvaluationStatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                # TODO: narrow down
                Resource: "*"
        - PolicyName: StatesLogPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DeleteResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                  - logs:CreateLogGroup
                Resource: "*"
  EvaluateLLMStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: Evaluate-LLM
      DefinitionString:
        Fn::Sub:
          - |-
            {
              "Comment": "Invoke LLM state machine",
              "StartAt": "validate_inputs",
              "States": {
                "validate_inputs": {
                  "Type": "Task",
                  "Resource": "arn:aws:states:::lambda:invoke",
                  "OutputPath": "$.Payload",
                  "Parameters": {
                    "Payload.$": "$",
                    "FunctionName": "${ValidateInputLambdaArn}"
                  },
                  "Retry": [
                    {
                      "ErrorEquals": [
                        "States.ALL"
                      ],
                      "IntervalSeconds": 1,
                      "MaxAttempts": 3,
                      "BackoffRate": 2
                    }
                  ],
                  "Next": "Map"
                },
                "Map": {
                  "Type": "Map",
                  "ItemProcessor": {
                    "ProcessorConfig": {
                      "Mode": "INLINE"
                    },
                    "StartAt": "evaluate_llm",
                    "States": {
                      "evaluate_llm": {
                        "Type": "Task",
                        "Resource": "arn:aws:states:::lambda:invoke",
                        "Parameters": {
                          "FunctionName": "${EvaluateLLMArn}",
                          "Payload": {
                            "execution_id.$": "$$.Execution.Id",
                            "input.$": "$"
                          }
                        },
                        "Retry": [
                          {
                            "ErrorEquals": [
                              "States.ALL"
                            ],
                            "IntervalSeconds": 1,
                            "MaxAttempts": 3,
                            "BackoffRate": 2
                          }
                        ],
                        "End": true,
                        "ResultSelector": {
                          "result.$": "$.Payload"
                        },
                        "ResultPath": "$.result"
                      }
                    }
                  },
                  "ItemsPath": "$.result",
                  "Next": "summarize_result"
                },
                "summarize_result": {
                  "Type": "Task",
                  "Resource": "arn:aws:states:::lambda:invoke",
                  "OutputPath": "$.Payload",
                  "Parameters": {
                    "Payload.$": "$",
                    "FunctionName": "${EvaluateLLMSummaryArn}"
                  },
                  "Retry": [
                    {
                      "ErrorEquals": [
                        "States.ALL"
                      ],
                      "IntervalSeconds": 1,
                      "MaxAttempts": 3,
                      "BackoffRate": 2
                    }
                  ],
                  "End": true
                }
              }
            }
          - {
            ValidateInputLambdaArn: !GetAtt ValidateLLMEvaluateInput.Arn,
            EvaluateLLMArn: !GetAtt EvaluateLLM.Arn,
            EvaluateLLMSummaryArn: !GetAtt EvaluationResultSummary.Arn
          }
      RoleArn: !GetAtt LLMIEvaluationStatesExecutionRole.Arn
  InvokeLLM:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: invoke_llm_lambda
      Handler: invoke_llm_handler.handler
      Runtime: python3.9
      CodeUri: ../
      MemorySize: 1024
      VpcConfig:
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
        SecurityGroupIds:
          - !Ref SecurityGroup
      Timeout: 100
      Environment:
        Variables:
          ResultBucket: !Sub '${EvaluationBucket}'
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python39:10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                # TODO narrow down
                - s3:*
                - bedrock:*
                - sagemaker:*
              Resource: "*"
  EvaluateLLM:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: evaluate_llm_lambda
      Handler: evaluate_llm_handler.handler
      Runtime: python3.9
      CodeUri: ../
      MemorySize: 1024
      VpcConfig:
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
        SecurityGroupIds:
          - !Ref SecurityGroup
      Environment:
        Variables:
          ResultBucket: !Sub '${EvaluationBucket}'
      Timeout: 200
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python39:10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                # TODO narrow down
                - s3:*
                - bedrock:*
                - sagemaker:*
                - dynamodb:GetItem
                - dynamodb:Query
              Resource: "*"
  ConvertToJson:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: invoke_llm_convert_to_json
      Handler: invoke_llm_convert_to_json.handler
      Runtime: python3.9
      CodeUri: ../
      MemorySize: 1024
      Timeout: 5
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python39:10
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                # TODO narrow down
                - logs:*
              Resource: "*"

  ValidateLLMEvaluateInput:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: evaluate_llm_input_validation
      Handler: evaluate_llm_input_validation.handler
      Runtime: python3.9
      CodeUri: ../
      MemorySize: 1024
      Timeout: 5
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                # TODO narrow down
                - s3:*
                - dynamodb:GetItem
                - dynamodb:Query
              Resource: "*"

  EvaluationResultSummary:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: evaluate_llm_result_summary
      Handler: evaluate_llm_result_summary.handler
      Runtime: python3.9
      CodeUri: ../
      MemorySize: 1024
      Timeout: 30
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python39:10
      Environment:
        Variables:
          ResultBucket: !Sub '${EvaluationBucket}'
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                # TODO narrow down
                - s3:*
              Resource: "*"


  SolutionTableDDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "PK"
          AttributeType: "S"
        -
          AttributeName: "SK"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "PK"
          KeyType: "HASH"
        -
          AttributeName: "SK"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "SolutionTableDDB"